language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: TND8z8w3jFLhgeL/Eh1Wx0acfEcN6tbuZfb19c/ajztJyDwk68ET4R4qmM3OG2FxKcGTsMxB4jt1qPk74msNTPgP1Wab0l/D5H1OLvzb2mmpPupo/VCFAMwjvhrqitxbRaUtgNUUYcY8PnA8l4pmOMxziwGOegYNwAVrHgiAuWB5+kMHKTe/PMILT9RcS/+M9Yoz+32nQyuUGlTrOTlTNc85Yk2LZ7i0IracrY4iPFGhzrmqOnrRlUOvQlQ/E5gNIdlZ94QkyWbx67Dy5UbyFoahyxmfNTBNpIEw1Cg/M0dfl1zgx2hclCXeIE1Az79PENpM4AyjjgiISmqp0UWp/iGaSkkr2jtmrBvGNEyOlz82yEyR4mn67YMcIE5NDvfA2CSx4u9I+koRW2y8EYvnluPysjJ1mRWo0REBKqJ0E2fgfEKsDxlWooegwoEUvE2apUHRY1tq261Ong4YrkSIPBGkfzooe39BwINw6qMGEUWECUfHDcFN7OeR7IwqX4W10HgKPzrRQh+34BIlVLda83JWvQseujXZ+ECOPFmqiX0gK7MWoz66leLaNgh4bn9TykHvfg9M1uSgdBMUGSOIlWME8PY4BrMNf7hdo1ha3FWe4H4+teEfg5fbLYxRhf27jcaJG59IVy5BlhRnT8T4IMGgYa2QiUcyC+e86tY6WX4=
  app: flaskci
